site_name: Pcaparser
repo_url: https://github.com/Zaf1ro/Pcaparser
repo_name: 'GitHub'
site_author: Jason Duan
pages:
- Introduction: intro.md
- Example:
  - 'Print Pcap Header Example': 'example/pcap.md'
  - 'Print Ethernet Example': 'example/eth.md'
  - 'Print IP Example': 'example/ip.md'
  - 'Print TCP Example': 'example/tcp.md'
- API Reference: API.md
- Protocol: protocol.md
- License: license.md
theme: readthedocs